# Generated by Django 3.2.7 on 2021-09-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='description',
        ),
    ]
