# Generated by Django 3.2.7 on 2021-09-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_remove_realtor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
