# Generated by Django 3.2.7 on 2021-09-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_realtor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
